apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.labels.app }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: {{ .Values.labels.app }}